version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: sidhra/sept-takehome
    docker:
      - image: circleci/node:10
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    working_directory: ~/circleci-node
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run: npm install
      - run: docker build -t $IMAGE_NAME:latest .
      - run: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 19.03.13
      - run: docker load -i /tmp/workspace/image.tar
      - run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
        filters:
          branches:
            only: master
      - publish-latest:
        requires:
          - build
        filters:
          branches:
            only: master