version: 2.1

jobs:
  build:
    environment:
      IMAGE_NAME: sidhra/sept-takehome
    working_directory: ~/circleci-node
    docker:
      - image: "circleci/node:10"
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run: npm install
      - run: docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
        filters:
          branches:
            only: master